apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: github-actions-react
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: github-actions-react
    spec:
      containers:
        - name: github-actions-react
          image: gcr.io/metro-op-2tier-internal/github-actions-react@sha256:d17e77a7ff6cea1ccf00f8ad13bc1264f8bd570def845ec2c69092e67662320b
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 250m