apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: github-actions-react
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: github-actions-react
    spec:
      containers:
        - name: github-actions-react
          image: gcr.io/metro-op-2tier-internal/github-actions-react@sha256:45d0c1da1264e2de5a83e584b45d201ad927ac8f15041d800058e441a7f7d7c7
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 250m